name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  ## What’s Changed

  NEXT_PATCH_VERSION: $NEXT_PATCH_VERSION
  NEXT_MINOR_VERSION: $NEXT_MINOR_VERSION
  NEXT_MAJOR_VERSION: $NEXT_MAJOR_VERSION
  RESOLVED_VERSION: $RESOLVED_VERSION

  $CHANGES