<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WixToolset.Extensibility" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PowerShellLibrary\PowerShellLibrary.wixproj" ReferenceOutputAssembly="false" SkipGetTargetFrameworkProperties="true" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="PowerShellWixExtensionSchema.xsd" />
    <EmbeddedResource Include="TableDefinitions.xml" />
    <EmbeddedResource Include="..\PowerShellLibrary\bin\x86\$(Configuration)\PowerShellLibrary.wixlib" Link="PowerShellLibrary.wixlib" />
  </ItemGroup>

  <Target Name="AfterBuild">
    <Copy SourceFiles="$(TargetDir)$(TargetName).pdb;$(TargetPath)" DestinationFolder="..\Libs" SkipUnchangedFiles="true" />
    <MakeDir Directories="..\NuGet\tools\lib" Condition="!Exists('..\NuGet\tools\lib')" />
    <Copy SourceFiles="$(TargetDir)$(TargetName).pdb;$(TargetPath)" DestinationFolder="..\NuGet\tools\lib" SkipUnchangedFiles="true" />
  </Target>
</Project>