name: Publish

on:
  release:
    types: # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#release
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
 
    steps:  
      # - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      #   with:
      #     config: ${{ vars.PERMISSIONS_CONFIG }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Download Assets
        uses: i3h/download-release-asset@v1.3.3
        with:
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          tag: ${{ github.event.release.tag_name }}
          file: '/.*\.nupkg/'
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - run: ls -alR
        name: List files

      - name: Publish the package to nuget.org
        run: dotnet nuget push "*.nupkg" --source https://api.nuget.org/v3/index.json -k $NUGET_AUTH_TOKEN --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
