name: Publish

on:
  release:
    types: # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#release
      - published

jobs:
  publish:
    runs-on: windows-latest
 
    steps:  

      - name: Download Assets
        uses: i3h/download-release-asset@v1.2.0
        with:
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          tag: ${{ github.event.release.tag_name }}
          file: '/.*\.nupkg/'
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - run: dir -recurse

      - name: push
        run: nuget push *.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_API_KEY }}
    